# Generated by Django 5.0.6 on 2024-05-26 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="categories",
            table="category",
        ),
    ]
