# Generated by Django 5.0.6 on 2024-05-26 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0002_alter_categories_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterField(
            model_name="categories",
            name="name",
            field=models.CharField(max_length=150, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="categories",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, null=True, unique=True, verbose_name="URL"
            ),
        ),
        migrations.CreateModel(
            name="Manga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, unique=True, verbose_name="Name"),
                ),
                (
                    "name_in_jap",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Name_in_jap"
                    ),
                ),
                (
                    "categories",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Categories"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Desciption"),
                ),
                (
                    "status",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Status"
                    ),
                ),
                (
                    "author",
                    models.TextField(blank=True, null=True, verbose_name="Author"),
                ),
                (
                    "magazine",
                    models.TextField(blank=True, null=True, verbose_name="Magazine"),
                ),
                (
                    "published",
                    models.TextField(
                        blank=True, null=True, verbose_name="Publish_Date"
                    ),
                ),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
                ),
                (
                    "views",
                    models.DecimalField(decimal_places=0, default=0.0, max_digits=100),
                ),
                ("image", models.ImageField(upload_to="manga_images")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="read.categories",
                        verbose_name="Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manga",
                "verbose_name_plural": "Mangas",
                "db_table": "Manga",
            },
        ),
    ]
