# Generated by Django 5.0.6 on 2024-05-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0003_alter_categories_options_alter_categories_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manga",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, null=True, unique=True, verbose_name="URL"
            ),
        ),
    ]
