# Generated by Django 5.0.6 on 2024-05-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0004_manga_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="categories",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, null=True, verbose_name="URL"
            ),
        ),
        migrations.AlterField(
            model_name="manga",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="manga_images"),
        ),
        migrations.AlterField(
            model_name="manga",
            name="score",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name="manga",
            name="status",
            field=models.CharField(max_length=150, verbose_name="Status"),
        ),
    ]
