# Generated by Django 5.0.6 on 2024-05-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0005_alter_categories_name_alter_categories_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manga",
            name="categories",
            field=models.CharField(max_length=100, verbose_name="Categories"),
        ),
    ]
