# Generated by Django 5.0.6 on 2024-05-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0006_alter_manga_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="Types",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name="manga",
            name="categories",
        ),
        migrations.AddField(
            model_name="manga",
            name="categories",
            field=models.ManyToManyField(to="read.types"),
        ),
    ]
