# Generated by Django 5.0.6 on 2024-05-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0007_types_remove_manga_categories_manga_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="types",
            name="type",
            field=models.CharField(max_length=150),
        ),
    ]
