# Generated by Django 5.0.6 on 2024-05-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("read", "0008_alter_types_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="manga",
            name="number_of_chapters",
            field=models.DecimalField(
                decimal_places=0,
                default=0.0,
                max_digits=5,
                verbose_name="Number of Chapters",
            ),
        ),
    ]
